####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-dune-cmake
Description: DUNE build system for Open Porous Media
Version: 3.0-git
Label: 3.0-git
Maintainer: robertk@posteo.org
MaintainerName: Robert K
Url: https://github.com/dr-robertk/
Suggests: dune-common (>= 2.4)
